import { useState } from 'react';
import { Download, Check, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from './ui/button';
import { format, type RegistrationResult } from '../lib/api';
const Metric=({label,value,unit,id}:{label:string;value:string;unit:string;id:string})=><div className="metric-tile" data-testid={`metric-${id}`}><p className="label-mono" data-testid={`metric-${id}-label`}>{label}</p><p className="mt-2 flex flex-wrap items-baseline gap-2"><strong className="metric-value text-slate-100" data-testid={`metric-${id}-value`}>{value}</strong><span className="text-[10px] text-slate-500" data-testid={`metric-${id}-unit`}>{unit}</span></p></div>;
export const ResultsPanel=({run,selected,setSelected,onDownload}:{run:RegistrationResult|null;selected:number|null;setSelected:(index:number)=>void;onDownload:(artifact:string)=>void})=>{
  const [page,setPage]=useState(0);const [inliersOnly,setInliersOnly]=useState(true);
  const metrics=run?.metrics;const all=(run?.match_points||[]).filter(p=>!inliersOnly||p.status==='inlier');const pageCount=Math.max(1,Math.ceil(all.length/10));const current=Math.min(page,pageCount-1);const rows=all.slice(current*10,current*10+10);
  const status=run?.status;
  const statusNote=!run||status==='completed'?null:status==='queued'||status==='running'?{tone:'info',title:'Registration in progress',body:'Metrics and correspondences appear once the run finishes. This page will update automatically.'}:status==='cancelled'?{tone:'warn',title:'Run cancelled',body:'The run was cancelled before a transform was produced, so there are no metrics or match points.'}:{tone:'warn',title:'No valid transform found',body:`${run.diagnostics.join(' ')||'The engine could not find a reliable, unambiguous alignment.'} Empty metrics and match points are expected for a rejected run. Enter the frame's latitude/longitude to auto-fetch a closer regional LROC product, or upload a matching-scale reference — a whole-Moon context mosaic will not register a close-up frame.`};
  return <div className="mt-5" data-testid="results-panel-root">{statusNote&&<div className={`research-notice mb-4 ${statusNote.tone==='warn'?'error-notice':''}`} data-testid="results-status-note"><div className="font-medium" data-testid="results-status-title">{statusNote.title}</div><div className="mt-1 text-[11px] leading-5" data-testid="results-status-body">{statusNote.body}</div></div>}
  <div className="grid min-w-0 grid-cols-1 gap-6 xl:grid-cols-5">
    <section className="panel-card xl:col-span-2" data-testid="evaluation-metrics-panel"><p className="eyebrow" data-testid="evaluation-eyebrow">05 / EVALUATE</p><h2 className="section-title mb-3" data-testid="evaluation-heading">Registration quality</h2><div className="grid grid-cols-2 gap-1"><Metric label="Fitting RMSE" value={format(metrics?.rmse,3)} unit="reference px" id="rmse"/><Metric label="Inliers" value={metrics?`${metrics.inlier_count}`:'—'} unit={metrics?`/ ${metrics.total_matches} matches`:'points'} id="inlier-count"/><Metric label="Inlier ratio" value={metrics?format(metrics.inlier_ratio*100,1):'—'} unit="%" id="inlier-ratio"/><Metric label="Valid overlap" value={metrics?format(metrics.overlap*100,1):'—'} unit="% of valid reference" id="overlap"/><Metric label="Spatial coverage" value={metrics?format(metrics.spatial_coverage*100,1):'—'} unit="% · grid / hull" id="spatial-coverage"/><Metric label="Visual similarity" value={format(metrics?.image_similarity,1)} unit="index / 100" id="image-similarity"/></div><p className="mt-3 text-[10px] leading-5 text-slate-500" data-testid="similarity-definition">Similarity: valid-overlap intensity index, not an accuracy probability.</p><div className="mt-4 border-t border-slate-800 pt-4"><p className="label-mono" data-testid="checkpoint-accuracy-label">Independent-checkpoint accuracy</p><p className="mt-2 text-sm text-slate-200" data-testid="checkpoint-accuracy-value">{run?.checkpoint_accuracy?`${format(run.checkpoint_accuracy.rmse,3)} reference px · ${run.checkpoint_accuracy.count} checkpoints`:'N/A · no independent checkpoints'}</p></div>
    {metrics&&<dl className="mt-4 grid grid-cols-2 gap-2 text-[11px]" data-testid="transform-summary">{[['Δx',`${format(metrics.offset_x)} px`],['Δy',`${format(metrics.offset_y)} px`],['Rotation',`${format(metrics.rotation_deg)}°`],['Scale',`${format(metrics.scale_ratio,4)}×`],['Median residual',`${format(metrics.median_residual,3)} px`],['95th percentile',`${format(metrics.p95_residual,3)} px`]].map(([label,value],i)=><div key={label}><dt className="text-slate-500" data-testid={`transform-label-${i}`}>{label}</dt><dd className="mt-1 text-slate-200" data-testid={`transform-value-${i}`}>{value}</dd></div>)}</dl>}
    <div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>onDownload('report')} disabled={!run} data-testid="download-report-button"><Download size={13} className="mr-1"/>Diagnostics</Button><Button size="sm" variant="outline" onClick={()=>onDownload('geotiff')} disabled={!run?.quality_gate.export_allowed} data-testid="download-geotiff-button"><Download size={13} className="mr-1"/>GeoTIFF</Button></div><p className="mt-2 text-[10px] text-slate-500" data-testid="geotiff-band-note">GeoTIFF: original-resolution selected source band only.</p></section>
    <section className="panel-card min-w-0 xl:col-span-3" data-testid="match-points-panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow" data-testid="points-eyebrow">06 / CORRESPONDENCES</p><h2 className="section-title" data-testid="match-points-heading">Match point coordinates</h2></div><label className="flex items-center gap-2 text-[10px] text-slate-400"><input type="checkbox" checked={inliersOnly} onChange={e=>{setInliersOnly(e.target.checked);setPage(0);}} data-testid="inliers-only-toggle"/>Inliers only</label></div>
    <p className="mt-3 text-[10px] text-slate-500" data-testid="match-point-count-badge">{all.length} points · native pixel coordinates · all points in diagnostics</p>
    {rows.length?<div className="mt-4" data-testid="match-points-table"><div className="grid grid-cols-[28px_1fr_1fr_58px] gap-2 border-b border-slate-700 py-2 text-[9px] uppercase text-slate-500" data-testid="match-table-head"><span>#</span><span>Source x / y</span><span>Reference x / y</span><span>Residual</span></div>{rows.map(p=><button key={p.index} onClick={()=>setSelected(p.index)} className={`grid w-full grid-cols-[28px_1fr_1fr_58px] items-center gap-2 border-b border-slate-800 py-3 text-left text-[10px] ${selected===p.index?'bg-cyan-300/10':'hover:bg-white/5'}`} data-testid={`match-point-row-${p.index}`}><span className={p.status==='inlier'?'text-slate-500':'text-rose-300'}>{p.index}</span><span className="text-amber-200" data-testid={`match-point-source-coordinate-${p.index}`}>{format(p.source_x,2)}<br/>{format(p.source_y,2)}</span><span className="text-cyan-200" data-testid={`match-point-reference-coordinate-${p.index}`}>{format(p.reference_x,2)}<br/>{format(p.reference_y,2)}</span><span className="text-slate-300" data-testid={`match-point-residual-${p.index}`}>{format(p.residual_error,3)}<br/><span className="text-slate-500">px</span></span></button>)}<div className="mt-3 flex items-center justify-between"><span className="text-[10px] text-slate-500" data-testid="points-pagination">{current+1} / {pageCount}</span><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={()=>setPage(current-1)} disabled={current===0} aria-label="Previous points" data-testid="points-prev"><ChevronLeft size={14}/></Button><Button size="icon" variant="ghost" onClick={()=>setPage(current+1)} disabled={current+1>=pageCount} aria-label="Next points" data-testid="points-next"><ChevronRight size={14}/></Button></div></div></div>:<p className="flex min-h-44 items-center justify-center text-xs text-slate-500" data-testid="match-points-empty-state">No correspondence set yet</p>}
    </section>
  </div></div>;
};
export const GateSummary=({run}:{run:RegistrationResult|null})=><div className="mt-4 border-t border-slate-800 pt-3" data-testid="threshold-evaluation">{run?.quality_gate.checks.map(check=><div key={check.key} className="flex items-start justify-between gap-3 py-1.5 text-[11px]" data-testid={`threshold-check-${check.key}`}><span className="text-slate-400">{check.label}</span><span className={check.passed?'text-emerald-300':'text-rose-300'} data-testid={`threshold-check-${check.key}-status`}>{check.passed?<Check size={13}/>:<X size={13}/>}</span></div>)}<p className={`mt-3 text-xs ${run?.quality_gate.export_allowed?'text-emerald-300':'text-amber-200'}`} data-testid="threshold-gate-status">{run?(run.quality_gate.export_allowed?'Checks passed · GeoTIFF available':'GeoTIFF blocked · diagnostics available'):'Not evaluated'}</p></div>;