import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocation, useNavigate } from 'react-router-dom';
import { ShieldCheck, Split, CheckCircle2, AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';
import { WorkspaceHeader } from '../components/WorkspaceHeader';
import { SourceControls } from '../components/SourceControls';
import { ReferenceControls } from '../components/ReferenceControls';
import { InspectionViewport } from '../components/InspectionViewport';
import { ResultsPanel } from '../components/ResultsPanel';
import { QualityControls } from '../components/QualityControls';
import ReferenceLibrary from './ReferenceLibrary';
import RunHistory from './RunHistory';
import { apiGet, apiPost, artifactUrl, downloadArtifact, isRunning, format, type RegistrationResult, type ReferenceRecord, type Capabilities } from '../lib/api';

export default function Home(){
 const client=useQueryClient();const location=useLocation();const navigate=useNavigate();
 const [sourceFile,setSourceFile]=useState<File|null>(null);const [sourcePreview,setSourcePreview]=useState<string|null>(null);const [referenceId,setReferenceId]=useState('');
 const [runId,setRunId]=useState<string|null>(()=>sessionStorage.getItem('moon-last-run'));const [run,setRun]=useState<RegistrationResult|null>(null);const [selectedPoint,setSelectedPoint]=useState<number|null>(null);
 const [method,setMethod]=useState('auto');const [sensor,setSensor]=useState('optical');const [band,setBand]=useState(1);const [refine,setRefine]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState('');const [comparisonIds,setComparisonIds]=useState<string[]>([]);
 const limits=useQuery({queryKey:['capabilities'],queryFn:()=>apiGet<Capabilities>('/registration/capabilities')});
 const references=useQuery({queryKey:['references'],queryFn:()=>apiGet<ReferenceRecord[]>('/catalog/references')});
 const runQuery=useQuery({queryKey:['run',runId],queryFn:()=>apiGet<RegistrationResult>(`/registration/runs/${runId}`),enabled:!!runId,retry:false,refetchInterval:query=>isRunning(query.state.data||null)?800:false});
 const comparison=useQuery({queryKey:['comparison',comparisonIds],queryFn:()=>Promise.all(comparisonIds.map(id=>apiGet<RegistrationResult>(`/registration/runs/${id}`))),enabled:comparisonIds.length>0,refetchInterval:query=>!query.state.data||query.state.data.some(isRunning)?1000:false});
 useEffect(()=>{if(runQuery.data)setRun(runQuery.data);},[runQuery.data]);
 useEffect(()=>{if(runId)sessionStorage.setItem('moon-last-run',runId);else sessionStorage.removeItem('moon-last-run');},[runId]);
 useEffect(()=>()=>{if(sourcePreview)URL.revokeObjectURL(sourcePreview);},[sourcePreview]);
 const update=(next:RegistrationResult)=>{setRun(next);setRunId(next.id);client.setQueryData(['run',next.id],next);};
 const clearResult=()=>{setRun(null);setRunId(null);setSelectedPoint(null);setError('');setComparisonIds([]);};
 const [autoRefBusy,setAutoRefBusy]=useState(false);
 const autoReference=async()=>{setAutoRefBusy(true);try{const ref=await apiPost<ReferenceRecord>('/catalog/auto-reference');setReferenceId(ref.id);await client.invalidateQueries({queryKey:['references']});toast.success((ref.from_cache?`Auto-matched cached ${ref.matched_product_title}`:`Auto-fetched ${ref.matched_product_title} from LROC`)+' · enter the frame lat/long for a closer regional match',{duration:6000});}catch(e){toast.error((e as Error).message);}finally{setAutoRefBusy(false);}};
 const handleFile=(file?:File)=>{if(!file)return;if(limits.data&&file.size>limits.data.max_upload_mib*1024**2){setError(`Upload exceeds ${limits.data.max_upload_mib} MiB.`);return;}if(!/\.(png|jpe?g|webp|tiff?)$/i.test(file.name)){setError('Unsupported file type. Native sensor containers and archives are not supported.');return;}setSourceFile(file);setSourcePreview(/\.(tiff?)$/i.test(file.name)?null:URL.createObjectURL(file));clearResult();if(!referenceId)autoReference();};
 const selectReference=(id:string)=>{if(isRunning(run)){toast.info('Wait or cancel the active run before switching references');return;}setReferenceId(id);clearResult();navigate('/');};
 const form=(engine:string)=>{if(!sourceFile||!referenceId)throw new Error('Select both source and reference.');const data=new FormData();data.append('source_image',sourceFile);data.append('reference_id',referenceId);data.append('source_band',String(band));data.append('sensor',sensor);data.append('method',engine);data.append('refine',String(refine));return data;};
 const submit=async(compare=false)=>{setSubmitting(true);setError('');setComparisonIds([]);try{const first=await apiPost<RegistrationResult>('/registration/run',form(compare?'sift':method));update(first);if(compare){const second=await apiPost<RegistrationResult>('/registration/run',form('orb'));setComparisonIds([first.id,second.id]);}toast.success(compare?'Both engines queued against the same reference':'Registration queued');}catch(e){setError((e as Error).message);}finally{setSubmitting(false);}};
 const cancel=async()=>{try{for(const id of comparisonIds.length?comparisonIds:runId?[runId]:[]){const current=await apiGet<RegistrationResult>(`/registration/runs/${id}`);if(isRunning(current))await apiPost(`/registration/runs/${id}/cancel`);}await client.invalidateQueries({queryKey:['run']});toast.info('Cancellation requested');}catch(e){setError((e as Error).message);}};
 const download=async(artifact:string)=>{if(!run)return;try{await downloadArtifact(`/api/registration/${run.id}/${artifact}`,`moon-${run.id}-${artifact}.${artifact==='geotiff'?'tif':'json'}`);}catch(e){toast.error((e as Error).message);}};
 const busy=submitting||isRunning(run)||autoRefBusy||!!comparison.data?.some(isRunning);const selectedReference=references.data?.find(r=>r.id===referenceId);const workspace=!['/runs','/references'].includes(location.pathname);
 return <main className="min-h-screen text-slate-100" data-testid="mission-control-dashboard"><WorkspaceHeader run={run} onReset={()=>{clearResult();setSourceFile(null);setSourcePreview(null);}} onExport={()=>download('report')}/>
 <div className="mx-auto max-w-[1600px] p-4 md:p-6 lg:p-8">
 {workspace?<><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end" data-testid="mission-introduction"><div><p className="eyebrow text-cyan-200" data-testid="mission-eyebrow">REGISTRATION WORKSPACE {run?`/ ${run.id.slice(0,8)}`:''}</p><h1 className="mt-2" data-testid="mission-title">Moon Match Points</h1><p className="mt-2 text-sm text-slate-400" data-testid="mission-description">Source → reference → registration → inspection → quality-gated export</p></div><span className="flex items-center gap-2 text-[10px] text-slate-400" data-testid="single-operator-badge"><ShieldCheck size={14} className="text-amber-200"/>SINGLE-OPERATOR RESEARCH PROTOTYPE</span></div>
 <p className="research-notice mb-6" data-testid="research-release-notice">Native OHRC, TMC-2 and IIRS support unverified · original samples and acceptance tolerances pending. Shared organisational use is blocked until access controls are added.</p>
 {(error||runQuery.isError)&&<p role="alert" className="research-notice error-notice mb-5" data-testid="registration-error">{error||(runQuery.error as Error)?.message}</p>}
 {run&&!isRunning(run)&&<div className={`research-notice mb-5 ${run.status==='completed'?'':'error-notice'}`} data-testid="run-outcome"><div className="flex items-center gap-2 font-medium" data-testid="run-outcome-title">{run.quality_gate.export_allowed?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} {run.status==='completed'?(run.quality_gate.export_allowed?'Registration checks passed':'Diagnostic solution · GeoTIFF blocked'):run.status==='cancelled'?'Run cancelled':'Registration rejected'}</div><div className="mt-1" data-testid="run-outcome-detail">{run.diagnostics.join(' ')}</div></div>}
 <div className="grid min-w-0 grid-cols-1 gap-7 lg:grid-cols-12"><aside className="space-y-5 lg:col-span-4" data-testid="source-reference-column"><SourceControls file={sourceFile} onFile={handleFile} method={method} setMethod={setMethod} band={band} setBand={setBand} sensor={sensor} setSensor={setSensor} refine={refine} setRefine={setRefine} run={run} onRun={()=>submit()} onCompare={()=>submit(true)} onCancel={cancel} canRun={!!sourceFile&&!!referenceId&&!!limits.data} busy={busy} capabilities={limits.data}><ReferenceControls selected={referenceId} onSelect={selectReference} busy={busy}/></SourceControls><QualityControls run={run} onUpdate={update} onAdjustment={next=>{update(next);setComparisonIds([]);}}/></aside>
 <section className="min-w-0 lg:col-span-8" data-testid="registration-workspace"><InspectionViewport run={run} sourcePreview={sourcePreview} referencePreview={selectedReference?artifactUrl(selectedReference.image_url):undefined} selected={selectedPoint}/><ResultsPanel run={run} selected={selectedPoint} setSelected={setSelectedPoint} onDownload={download}/>
 <section className="panel-card mt-5" data-testid="engine-comparison-panel"><div className="flex items-center gap-2"><Split size={15} className="text-cyan-200"/><h2 className="section-title" data-testid="engine-comparison-heading">SIFT versus ORB</h2></div>{comparison.data?<div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2" data-testid="engine-comparison-report">{comparison.data.map(engine=><div key={engine.id} className="border-l-2 border-slate-700 pl-4" data-testid={`engine-card-${engine.requested_method}`}><div className="flex justify-between"><p className="text-sm text-slate-200" data-testid={`engine-name-${engine.requested_method}`}>{engine.requested_method.toUpperCase()}</p><span className="text-[10px] text-slate-400" data-testid={`engine-status-${engine.requested_method}`}>{engine.status}</span></div><p className="mt-2 text-xs text-slate-400" data-testid={`engine-metrics-${engine.requested_method}`}>Fitting RMSE {format(engine.metrics?.rmse,3)} px<br/>{engine.metrics?.inlier_count||0} inliers · overlap {engine.metrics?format(engine.metrics.overlap*100,1):'N/A'}%<br/>{format(engine.elapsed_seconds,1)} s · {engine.quality_gate.export_allowed?'export allowed':'export blocked'}</p>{engine.status==='failed'&&<p className="mt-2 text-[10px] text-rose-300" data-testid={`engine-failure-${engine.requested_method}`}>{engine.diagnostics.join(' ')}</p>}<Button size="sm" variant="ghost" className="mt-2" disabled={isRunning(engine)} onClick={()=>update(engine)} data-testid={`engine-select-${engine.requested_method}`}>Inspect {engine.requested_method.toUpperCase()}</Button></div>)}</div>:<p className="mt-4 text-xs text-slate-500" data-testid="engine-comparison-empty-state">No paired engine runs recorded in this session.</p>}</section>
 {run&&<details className="mt-6 border-t border-slate-800 pt-4" data-testid="run-provenance-panel"><summary className="cursor-pointer text-xs text-cyan-200" data-testid="run-provenance-trigger">Run provenance & raster metadata</summary><div className="mt-4 space-y-2 break-all text-[10px] leading-5 text-slate-500" data-testid="run-provenance-content"><p>Source SHA-256: {run.source_sha256}</p><p>Reference SHA-256: {run.reference_sha256}</p><p>Reference: {run.reference_provenance}</p><p>{run.reference_metadata?.georeferencing_note}</p><p>Source band: {run.source_metadata?.selected_band||band} · {run.source_metadata?.dtype||'not decoded'}</p><p>Reference band: {run.reference_metadata?.selected_band} · {run.reference_metadata?.dtype}</p><p>{run.parent_run_id?`Re-evaluated adjustment of ${run.parent_run_id}`:'Original run'} · complete software versions and transforms in diagnostics</p></div></details>}
 </section></div></>:location.pathname==='/references'?<ReferenceLibrary onSelect={selectReference}/>:<RunHistory onOpen={row=>{update(row);setReferenceId(row.reference_id);navigate('/');}}/>}
 <footer className="mt-8 flex flex-wrap items-center justify-between gap-2 border-t border-slate-800 pt-4 text-[10px] text-slate-500" data-testid="mission-footer"><span data-testid="footer-product">Moon Match Points / research workstation</span><span data-testid="footer-method-note">Local affine geometry · provisional acceptance · no accuracy guarantee</span></footer>
 </div></main>;
}